### PR TITLE
Load an LP64 backend the new version of Clp_jll.jl

### PR DESCRIPTION
**Pull request by amontoison**

### CODE REVIEW

**Comment by amontoison** [comment]
@odow 
Can you trigger this CI builds?

**Comment by odow** [comment]
I guess this is needed, but it is unrelated to the aarch64-apple stuff.

**Comment by amontoison** [comment]
> I guess this is needed, but it is unrelated to the aarch64-apple stuff.

We should try to use a version of `Clp` compiled in debug mode but I highly suspect that the issue is upstream.

**Comment by odow** [comment]
See https://github.com/jump-dev/Clp.jl/issues/131#issuecomment-2235172720

**Review by odow — APPROVED** [review]

**Comment by amontoison** [comment]
> I guess this is needed, but it is unrelated to the aarch64-apple stuff.

I'm 99% sure that they never tested the compilation of Clp with `Clang` on Apple Silicon and always tested with `gcc`.
`gcc` was needed during a very long time because of incomplete support of OpenMP with the `Clang` compiler.

**Pull request merged**
